title: 'Style Guide NYU Libraries'
baseurl: '/library.nyu.edu-style_guide'
prose:
  siteurl: https://nyulibraries.github.io/library.nyu.edu-style_guide/
  media: images
  rooturl: _guides
  ignore:
    - /_layouts
    - /_includes
    - _config.yml
    - index.html
  metadata:
    _guides:
      - name: layout
        field:
          value: guide
          element: select
          options:
            - name: Guide (preview + code example)
              value: guide
            - name: Article (raw content)
              value: article
          help: "Choose guide (preview + code example) or article (raw content) layouts."
      - name: "title"
        field:
          element: text
          label: title
collections:
  guides:
    title: Guides
    output: true
    permalink: "/:collection/:path/"
defaults:
- scope:
    path: ""
    type: guides
  values:
    layout: guide
    breadcrumbs: true
